### ISSUE TITLE
See if https://github.com/gopherjs/websocket/issues/13 can be resolved.

### ISSUE THREAD

**Issue by dmitshur** [shurcooL/backlog#26]
There's a pretty detailed and insightful analysis posted at https://github.com/gopherjs/websocket/issues/13#issuecomment-226376235. It should be enough to go on and see if the issue can be fixed.

**Comment by theclapp** [comment]
See also gopherjs/gopherjs#478.

**Comment by dmitshur** [comment]
Thanks for the heads up. :)

**Comment by dmitshur** [comment]
This issue is easiest to resolve when actively working with websocket package. I'm not doing that in the foreseeable near future. When I do get around to it, the issue is being tracked upstream in gopherjs/websocket#13, so I'd rather just deal with it there.

Closing as "not done".
