### ISSUE TITLE
Maybe make CL for cmd/gofmt usage of os.Exit.

### ISSUE THREAD

**Issue by dmitshur** [shurcooL/backlog#4]
See https://github.com/mdempsky/unconvert/commit/3b9aa41c71a855a5f5fee96dc751979ce6e8cbbe#commitcomment-16225884.

**Comment by dmitshur** [comment]
As mentioned in that comment,

> FYI, it seems like it's relatively common in the main repo:
> 
> ```
> $ git grep -B1 os.Exit | grep -A1 PrintDefaults
> ```

The output is:

```
go $ git grep -B1 os.Exit | grep -A1 PrintDefaults
doc/progs/run.go-       flag.PrintDefaults()
doc/progs/run.go:       os.Exit(2)
--
src/cmd/asm/internal/flags/flags.go-    flag.PrintDefaults()
src/cmd/asm/internal/flags/flags.go:    os.Exit(2)
--
src/cmd/cgo/main.go-    flag.PrintDefaults()
src/cmd/cgo/main.go:    os.Exit(2)
--
src/cmd/dist/main.go-               flag.PrintDefaults()
src/cmd/dist/main.go:               os.Exit(2)
--
src/cmd/doc/main.go-    flag.PrintDefaults()
src/cmd/doc/main.go:    os.Exit(2)
--
src/cmd/gofmt/gofmt.go- flag.PrintDefaults()
src/cmd/gofmt/gofmt.go: os.Exit(2)
--
src/cmd/objdump/main.go-    flag.PrintDefaults()
src/cmd/objdump/main.go:    os.Exit(2)
--
src/cmd/vet/main.go-    flag.PrintDefaults()
src/cmd/vet/main.go:    os.Exit(2)
--
src/go/printer/testdata/linebreaks.golden-  flag.PrintDefaults()
src/go/printer/testdata/linebreaks.golden:  os.Exit(2)
--
src/go/printer/testdata/linebreaks.input-   flag.PrintDefaults()
src/go/printer/testdata/linebreaks.input:   os.Exit(2)
--
src/go/types/gotype.go- flag.PrintDefaults()
src/go/types/gotype.go: os.Exit(2)
--
src/syscall/mksyscall_windows.go-   flag.PrintDefaults()
src/syscall/mksyscall_windows.go:   os.Exit(1)
```

For the same reason as in https://github.com/shurcooL/backlog/issues/12#issuecomment-214039265, I am going to close this and not do it. Fixing it in one place is not as valuable as fixing it everywhere, and fixing it everywhere is hard to verify it introduces no unintended bugs. Unfortunate, but I can't afford to get to this anytime soon.

**Comment by dmitshur** [comment]
This issue has been reincarnated as https://github.com/dominikh/go-staticcheck/issues/67.

**Comment by dgryski** [comment]
Is there an issue on the Go bug tracker for this?

**Comment by dmitshur** [comment]
For what exactly? Not that I know of.
